spring:
    application:
        name: service-movie-stream
    main:
        web-application-type: REACTIVE
    r2dbc:
        password: ${SPRING_DATASOURCE_PASSWORD}
        url: r2dbc:${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
    data:
        r2dbc:
            repositories:
                enabled: true
    webflux:
        base-path: /movie-stream
server:
    port: 8000
    servlet:
        context-path: /movie-stream
    use-forward-headers: true